seata:
  ip: 127.0.0.1 # ğŸ“ æ ¸å¿ƒï¼šå†™æ­»æ³¨å†Œ IP
  port: 8091

  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: nacos:8848
      group: SEATA_GROUP
      namespace: "" # ç•™ç©º

  config:
    type: nacos
    nacos:
      server-addr: nacos:8848
      group: SEATA_GROUP
      namespace: "" # ç•™ç©º

  store:
    mode: file

server:
  port: 7091 # Web ç«¯å£

logging:
  file:
    path: /root/logs/seata