server:
  port: 8086

spring:
  application:
    name: platform-file-service
  datasource:
    url: jdbc:mysql://localhost:3306/manuflex_paas?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: manuflex_user
    password: manuflex_password
    driver-class-name: com.mysql.cj.jdbc.Driver

# MinIO 配置
minio:
  endpoint: http://localhost:9000 # 容器内部通信用 minio，本地用 localhost
  access-key: minioadmin
  secret-key: minioadminpassword
  bucket-name: manuflex-files
  external-endpoint: http://localhost:9000 # 前端访问的地址 (如果前端直连)

app:
  jwt:
    # 公钥（网关和所有资源服务都需要配置）
    publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuBPMYYuTlJWVajcWkg9FkGQg7Pxpid0tHJl8dG+ruECca8T4WV87e7DvN4OZxUbongp4P4KgG1xHGXswMV9EpK2GnOx2BbHTh+yU3uI2JucpOZQL3uWcKQ+cZIgMIHWDrQ/660ueyLwxxDXoytZaKYW/OGzUEAZxtByLuhO6MWXyMgfi8RoNNOZOxFmyk1G59hF6MLqcC+4j452oCa6woz9HrfhK3DAwuBFfQerM/eYLvShx5p92/xKseSwa3j6Wve1zAY3ZH/wv/TXdQJ18ykaqXkw6qn9ELzh6Hg2ACTDu9k7hs67M9JWKIkQZe6DrOBNjVD5ZRoEkA+ulZiZetQIDAQAB
    expirationMs: 3600000 # Access Token 过期时间，例如 1 小时 (3600 * 1000 毫秒)
    refreshExpirationMs: 86400000 # Refresh Token 过期时间，例如 7 天 (7 * 24 * 3600 * 1000 毫秒)


file:
  # 这里配置您的网关地址 (宿主机访问地址)
  gateway-url: http://localhost:8086

# Qdrant 配置

qdrant:
  host: localhost
  port: 6334
  collection-name: knowledge_768

# gemini 配置
gemini:
  api-key: ${GEMINI_API_KEY:}
  model: gemini-2.5-flash
  embedding-model: text-embedding-004

# 文档处理配置
document:
  chunk-size: 500
  chunk-overlap: 50