server:
  port: 8086

spring:
  application:
    name: platform-file-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:localhost}:8848
        namespace: ${NACOS_NAMESPACE:}
      config:
        server-addr: ${NACOS_HOST:localhost}:8848
        file-extension: yml
        group: DEFAULT_GROUP
        namespace: ${NACOS_NAMESPACE:}
        refresh-enabled: true

  config:
    import:
      # 告诉 Spring Boot 去 Nacos 找名为 "platform-file-service.yml" 的配置
      - nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
