server:
  port: 8087

spring:
  application:
    name: platform-agent-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:localhost}:8848
        namespace: ${NACOS_NAMESPACE:}
      config:
        server-addr: ${NACOS_HOST:localhost}:8848
        file-extension: yml
        group: DEFAULT_GROUP
        namespace: ${NACOS_NAMESPACE:}
        refresh-enabled: true

  config:
    import:
      - nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}