spring:
  application:
    name: platform-agent-service

  datasource:
    url: jdbc:mysql://localhost:3306/manuflex_paas?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: manuflex_user
    password: manuflex_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    # 公钥（网关和所有资源服务都需要配置）
    publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuBPMYYuTlJWVajcWkg9FkGQg7Pxpid0tHJl8dG+ruECca8T4WV87e7DvN4OZxUbongp4P4KgG1xHGXswMV9EpK2GnOx2BbHTh+yU3uI2JucpOZQL3uWcKQ+cZIgMIHWDrQ/660ueyLwxxDXoytZaKYW/OGzUEAZxtByLuhO6MWXyMgfi8RoNNOZOxFmyk1G59hF6MLqcC+4j452oCa6woz9HrfhK3DAwuBFfQerM/eYLvShx5p92/xKseSwa3j6Wve1zAY3ZH/wv/TXdQJ18ykaqXkw6qn9ELzh6Hg2ACTDu9k7hs67M9JWKIkQZe6DrOBNjVD5ZRoEkA+ulZiZetQIDAQAB
    expirationMs: 3600000 # Access Token 过期时间，例如 1 小时 (3600 * 1000 毫秒)
    refreshExpirationMs: 86400000 # Refresh Token 过期时间，例如 7 天 (7 * 24 * 3600 * 1000 毫秒)

ai:
  provider: ${AI_PROVIDER:openai}

# gemini 配置
gemini:
  api-key: ${GEMINI_API_KEY:}
  model: gemini-2.5-flash

openai:
  api-key: ${OPENAI_API_KEY:}
  model: ${OPENAI_MODEL:gpt-4o}
  base-url: ${OPENAI_BASE_URL:https://api.openai.com/v1}

logging:
  file:
    # 确保这是 Promtail 映射的主机路径
    name: ./logs/agent/application.log
  level:
    root: INFO
    org.springframework.web: INFO
    top.itangbao.platform.data: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE