spring:
  application:
    name: platform-agent-service

  datasource:
    url: jdbc:mysql://localhost:3306/manuflex_paas?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: manuflex_user
    password: manuflex_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  jwtSecret: xi5G429vyD9/rLxktYqsZU723o3V5OB65KWoU76ORtFqihOS3gSQSqEWfDzDdc1ThsPv9D2v0AdqvcdXg+2vqg==
  jwtExpirationMs: 3600000 # Access Token 过期时间，例如 1 小时 (3600 * 1000 毫秒)
  jwtRefreshExpirationMs: 604800000 # Refresh Token 过期时间，例如 7 天 (7 * 24 * 3600 * 1000 毫秒)

# gemini 配置
gemini:
  api-key: ${GEMINI_API_KEY:}
  model: gemini-2.5-flash

logging:
  file:
    # 确保这是 Promtail 映射的主机路径
    name: ./logs/agent/application.log
  level:
    root: INFO
    org.springframework.web: INFO
    top.itangbao.platform.data: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE